version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws sts get-caller-identity
  build:
    commands:
      - echo Deploying API Gateway...
      - export API_ID=$(aws apigateway get-rest-apis --query "items[?name=='MyApi'].id" --output text)
      - echo API Gateway ID = "${API_ID}"
      - aws apigateway create-deployment --rest-api-id "${API_ID}" --stage-name dev
  post_build:
    commands:
      - echo Deployment complete.
artifacts:
  files:
    - '**/*'