version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - echo "Running integration tests..."
      - |
        # Run tests and capture output and exit status
        npm test > test_output.txt 2>&1
        echo $? > test_exit_code.txt
  post_build:
    commands:
      - |
        # Read the exit status and test output from files
        test_exit_code=$(cat test_exit_code.txt)

        # Function to escape JSON special characters
        escape_json() {
          echo "$1" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
        }

        send_slack_notification() {
          local status="$1"
          local message
          if [ "$status" = "SUCCESS" ]; then
          message="✅ *Build Succeeded*: The integration tests passed successfully."
          else
          # Extract only failed test case names from the output
          test_output=$(tail -n 500 test_output.txt)
          if [ -z "$test_output" ]; then
          test_output="No specific failed test cases found."
          fi
          message="🚫 *Build Failed*: The integration tests failed."
          fi
          echo "Sending Slack notification..."
          escaped_message=$(escape_json "$message")
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": $escaped_message, \"attachments\": [{\"text\": \"\`\`\`$test_output\`\`\`\"}]}" "$SLACK_WEBHOOK_URL"
        }

        if [ "$test_exit_code" -eq 0 ]; then
          send_slack_notification "SUCCESS"
        else
          send_slack_notification "FAILED"
        fi
artifacts:
  files:
    - "**/*"