version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - echo "Running integration tests..."
      - npm test
  post_build:
    commands:
      - |
        if [ $? -eq 0 ]; then
          STATUS="SUCCESS"
        else
          STATUS="FAILED"
        fi
        - echo "Fetching Slack Webhook URL from Secrets Manager..."
        - SLACK_WEBHOOK_URL=$(aws secretsmanager get-secret-value --secret-id SlackWebHookURL --query SecretString --output text)
        - echo "Sending notification to Slack..."
        - curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Integration Tests ${STATUS}!\"}" $SLACK_WEBHOOK_URL
artifacts:
  files:
    - "**/*"