version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - echo "Running integration tests..."
      - npm test
  post_build:
    commands:
      - |
        if [ $? -eq 0 ]; then
          STATUS="SUCCESS"
        else
          STATUS="FAILED"
        fi
        aws sns publish --topic-arn "arn:aws:sns:${AWS_REGION}:${CODEBUILD_ACCOUNT_ID}:TestResultsNotification" \
          --message "Integration Tests ${STATUS}."
artifacts:
  files:
    - "**/*"